version: '3.8'

services:
  snippetbox:
    build: .
    container_name: snippetbox
    ports:
      - "4000:4000"
    environment:
      - PORT=${PORT:-4000}
      - SNIPPETBOX_DB_DSN=${SNIPPETBOX_DB_DSN} 
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.services.portainer.loadbalancer.server.port=4000
      - traefik.http.routers.portainer.rule=Host(`snippetbox.guimochila.com`)
      - traefik.http.routers.portainer.entrypoints=web-secure
      - traefik.http.routers.portainer.tls=true
    networks:
      - public
      - private

networks:
  public:
    external: true
  private:
